entrega/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('inicio.urls')),
    path('admin/', admin.site.urls),
]

inicio/urls.py
from django.urls import path
from inicio import views

app_name = 'inicio' 

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('gatos/crear/', views.crear_gato, name='crear_gato')
]

inicio/models.py
from django.db import models

# Create your models here.

class Gato(models.Model):
    nombre = models.CharField(max_length=20)
    edad = models.IntegerField()
    fecha_nacimiento = models.DateField(null=True)

inicio/forms.py
from django import forms

class CrearGatoFormulario(forms.Form):
    nombre = forms.CharField(max_length=20)
    edad = forms.IntegerField()
    fecha_nacimiento = forms.DateField(required=False)

inicio/views.py
from django.shortcuts import render
from inicio.forms import CrearGatoFormulario
from inicio.models import Gato
# Create your views here.

def inicio(request):
    return render(request, 'inicio/inicio.html')

def crear_gato(request):
    mensaje = ''
    
    if request.method == 'POST':
        formulario = CrearGatoFormulario(request.POST)
        if formulario.is_valid():
            info = formulario.cleaned_data
            gato = Gato(nombre=info['nombre'], edad=info['edad'], fecha_nacimiento=info['fecha_nacimiento'])
            gato.save()
            mensaje = f'Se creó el gato {gato.nombre}'
            
        else:
            return render(request, 'inicio/crear_gato.html', {'formulario': formulario})    
    
    formulario = CrearGatoFormulario()
    return render(request, 'inicio/crear_gato.html', {'formulario': formulario})

inicio/templates/inicio/crear_gato.html
{% extends 'base.html' %}

{% block title_head %}
<title>Crear Gato</title>
{% endblock title_head %}

{% block h1_header %}
<h1>Crear Gato</h1>
{% endblock h1_header %}

{% block contenido %}

<p>{{mensaje}}</p>

<form action="" method="post">
    {% csrf_token %}
    <table>
        {{formulario}}
    </table>
    <button>Crear</button>
</form>
{% endblock contenido %}

inicio/templates/inicio/inicio.html
{% extends 'base.html' %}

{% block title_head %}
<title>Inicio</title>
{% endblock title_head %}

{% block h1_header %}
<h1>Bienvenidos!</h1>
{% endblock h1_header %}

{% block contenido %}
<p>
    Esta es la página desarrollada para la entrega.
</p>
{% endblock contenido %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        {% block title_head %}
        <title>Landing Page - Start Bootstrap Theme</title>
        {% endblock title_head %}
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href={% static 'css/styles.css' %} rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-light bg-light static-top">
            <div class="container">
                <a class="navbar-brand" href={% url 'inicio:inicio' %}>Inicio</a>ç
                <a class="btn btn-primary" href={% url 'inicio:crear_gato' %}>Crear Gato</a>
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container position-relative">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <div class="text-center text-white">
                            <!-- Page heading-->
                            <h1class="mb-5">
                            {% block h1_header %}
                            {% endblock h1_header %}
                        </h1>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        {% block contenido %}
        {% endblock contenido %}
        <!-- Footer-->
        <footer class="footer bg-light">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                        <ul class="list-inline mb-2">
                            <li class="list-inline-item"><a href="#!">About</a></li>
                        </ul>
                        <p class="text-muted small mb-4 mb-lg-0">&copy; Your Website 2023. All Rights Reserved.</p>
                    </div>
                    <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                        <ul class="list-inline mb-0">
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-facebook fs-3"></i></a>
                            </li>
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-twitter fs-3"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!"><i class="bi-instagram fs-3"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src={% static 'js/scripts.js' %}></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>